
import { FormData } from '../types';

export const HELP_TEXTS: { [key in keyof Partial<FormData> | string]: string } = {
  disadvantaged: 'Rendszeres gyermekvédelmi kedvezményre jogosultságról szóló jegyzői/gyámhatósági igazolás vagy határozat. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  multiplyDisadvantaged: 'Rendszeres gyermekvédelmi kedvezményre jogosultságról szóló igazolás, amelyben a halmozottan hátrányos helyzet is fel van tüntetve. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  disabled: 'ORSZI (vagy jogelőd) szakvéleménnyel ellátott igazolás, vagy a 87/2015. (IV. 9.) Korm. rendelet szerinti szakértői vélemény. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  largeFamily: 'Nagycsaládos státusz igazolása, pl. NOE tagsági, vagy az összes testvér diákigazolványa. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  familySupporter: 'A hallgatónak legalább egy gyermeke van (születési anyakönyvi kivonat), vagy ápolási díjra jogosult. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  orphanUnder25: 'Mindkét szülő halotti anyakönyvi kivonata, illetve árvaellátást igazoló dokumentum. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  halfOrphanUnder25: 'Egy szülő halotti anyakönyvi kivonata, illetve árvaellátást igazoló dokumentum. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  childCarer: 'CSED, GYES, GYED, GYET igazolása. Az adatot az adategyeztetés során rögzíteni kell a Neptunban.',
  fosterCare: 'Határozat tartós nevelésbe vételről, annak megszüntetéséről, vagy gyámügyi igazolás.',
  guardianshipEnded: 'A gyámság megszüntetéséről szóló jegyzői igazolás, vagy gyámügyi határozat.',
  orphanOver25: 'Mindkét szülő halotti anyakönyvi kivonata.',
  halfOrphanOver25: 'Egy szülő halotti anyakönyvi kivonata.',
  imaginedPaternity: 'Képzelt apaságról szóló határozat.',
  dependentSiblings: 'Ha nem vagy nagycsaládosként regisztrálva a Neptunban:\n• Tanuló korú testvér: iskolalátogatási/hallgatói jogviszony igazolás.\n• Nem tanuló korú testvér: születési anyakönyvi kivonat.',
  numberOfChildren: '• Tanuló korú gyermek: iskolalátogatási/hallgatói jogviszony igazolás.\n• Nem tanuló korú gyermek: születési anyakönyvi kivonat.',
  singleParent: 'Ha a válási határozaton szerepel gyermektartási díj, azt jövedelemként fel kell tüntetni. Ha nem, vagy eltérő a megfizetés, arról törvényes felszólítás/határozat vagy PPKE fejléces, két tanúval hitelesített büntetőjogi nyilatkozat szükséges.',
  caredForFamilyMembers: 'Ápolási díjra való jogosultságot megállapító járási hivatali határozat, vagy orvosi igazolás az ápolásra szorultságról.',
  supporterDisability: 'Komplex minősítési eljárás eredményéről szóló hatósági igazolás, mely tartalmazza a minősítési kategóriát (megváltozott munkaképesség).',
  supporterPensioner: 'A pályázat évére esedékes nyugdíjfolyósítói igazolás, vagy az utolsó 3 havi nyugdíjszelvény, vagy banki kivonat az utalásról.',
  supporterUnemployed: 'Két hónapnál nem régebbi, aktív álláskeresői státuszról szóló igazolás, valamint igazolás az álláskeresési járadékról/segélyről.',
  familyStatus: '• Elváltak: PPKE fejléces különélési nyilatkozat a tartásra kötelezettől (ha nem kap támogatást), két tanúval hitelesítve.\n• Házastárs az eltartó: Házassági anyakönyvi kivonat.',
  livingSituation: '• Albérlet: Nyomtatott, két tanúval, a bérlő és főbérlő aláírásával ellátott szerződés.\n• Saját lakás: Tulajdoni lap másolat (nem hiteles is lehet).\n• Szívességi: Két tanúval ellátott haszonkölcsön szerződés.\n• Kollégium: Kollégiumi/diákotthoni szerződés/igazolás.',
  distance: 'Hivatalos módszer: A távolságot a https://www.distance.to/ oldalon kell lemérni (légvonalban), és arról képernyőfotót kell csatolni PDF formátumban.\n\nAlternatív/régebbi módszer: Google Maps útvonaltervezővel (autós, legrövidebb út) készített képernyőfotó.',
  healthCosts: 'Fél évnél nem régebbi orvosi igazolás (havi bontásban), a gyógyszerek kiváltásáról szóló blokk/számla, és büntetőjogi nyilatkozat a gyógyszerek tételes felsorolásával.',
  selfSupporting: 'Minimum 10.000 Ft/hó jövedelem szükséges. Igazolni kell az utolsó 3 hónap jövedelmét. Szükséges továbbá a PPKE fejléces különélési nyilatkozat mindkét szülőtől, és a PPKE fejléces önellátó nyilatkozat.\n\nFontos: Önellátó hallgatók esetén a jövedelemigazolás részeként egy személyes beszélgetésen is részt kell venni a kari Szociális Bizottsággal.',
  otherSocialCircumstances: 'Manuálisan adható, max 10 pont. Pl.: Hiteltörlesztés, diákhitel visszafizetése, nem BNO-kódos betegség (pl. laktózérzékenység). A megadott adathoz igazoló dokumentumot kell feltölteni.',
  perCapitaIncome: 'A jövedelemigazolásokat a megfelelő időszakra kell benyújtani:\n• Őszi félév: június, július, augusztus havi nettó jövedelem.\n• Tavaszi félév: november, december, január havi nettó jövedelem.\nA munkáltatói igazoláson szerepelnie kell az aláírásnak és pecsétnek.',
};